version: '3.8'

services:
  mongo:
    container_name: exe-mongo
    image: mongo:7.0
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: exevipvl
    volumes:
      - mongo_data:/data/mongo-db

volumes:
  mongo_data:
    driver: local
